### ISSUE TITLE
用主机的idea的Kafka客户端连接docker服务 

### ISSUE THREAD

**Issue by poyun** [poyun/question#1]
# 问题
##### docker容器网络配置如下
```
networks:
  zk-net:
    name: zk-net   # 网络名
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/24
          gateway: 192.168.0.1
```
##### 服务是正常启动的
<img width="695" alt="image" src="https://user-images.githubusercontent.com/20579821/236656867-7ae62328-925a-49e1-ac52-04066079539a.png">

##### 防火墙状态如下
暂时无法查看， 防火墙操作命令不支持

### Q2:docker容器没有root权限及root密码无法更新软件
参考：[link](https://forums.docker.com/t/host-cannot-ping-container-ip/116919/8)

**Comment by poyun** [comment]
# 问题
### Q1:主机无法ping通docker容器
##### docker容器网络配置如下
```
networks:
  zk-net:
    name: zk-net   # 网络名
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/24
          gateway: 192.168.0.1
```
##### 服务是正常启动的
<img width="695" alt="image" src="https://user-images.githubusercontent.com/20579821/236656867-7ae62328-925a-49e1-ac52-04066079539a.png">

##### 防火墙状态如下
暂时无法查看 

### Q2:docker容器没有root权限及密码无法更新软件
